### ISSUE TITLE
Local DB setup

### ISSUE THREAD

**Issue by victorberestian** [google/webrisk#15]
Hi, i'm trying to use it on local machine but can't figure out how to setup local database file. As I understood from code it must be `gzip` archive but what must be inside archive?

**Comment by rdonuk** [comment]
Hi there, maybe it would help, there is a [repo ](https://bazi.github.io/gsb4j/) for Safe-Browsing, which is the free version of Web-Risk. Maybe the answer is there.

**Comment by victorberestian** [comment]
Thanks 👍

**Comment by victorberestian** [comment]
Duplicate of https://github.com/google/webrisk/issues/4
