### ISSUE TITLE
ListUpdate failure in database.go

### ISSUE THREAD

**Issue by ninoseki** [google/webrisk#29]
Hi, I just tried to run `wrserver` but I got the following error:

```bash
go get github.com/google/webrisk/cmd/wrserver

wrserver -apikey MY_API_KEY
webrisk: 2022/02/16 16:25:41 database.go:111: no database file specified
webrisk: 2022/02/16 16:25:41 database.go:218: ListUpdate failure (1): webrisk: unexpected server response code: 403
webrisk: 2022/02/16 16:25:41 webrisk_client.go:496: Next update in 29m6.45817924s
Starting server at localhost:8080
```

Probably something wrong with the API client implementation. Could you take a look at this issue, plase?

**Comment by bsurmanski** [comment]
The last time I saw this, API_KEY was set incorrectly. It should be the *Recaptcha* API key, not the google cloud API key.

see: https://github.com/google/webrisk/issues/28

**Comment by ninoseki** [comment]
Yes, you are correct. Thanks and sorry for taking your time.
