### ISSUE TITLE
Make cloud request configurable

### ISSUE THREAD

**Issue by heipei** [google/webrisk#6]
Hello Team,

could you make the request that is sent to the Cloud API configurable? What I mean is: If a URL lookup via hash is unsure via the local database and a request to the cloud has to be made (via sb.api.HashLookup), this request could also be made by passing the full URL instead, right? This should obviously not be the default behaviour, but hidden behind a feature flag.

Let me know what you think.

**Comment by heipei** [comment]
No, what I mean is: When wrserver has a local match for a hash-prefix, the verification should be done by using the full Lookup API (urls.search) against the Google server. My use-case is that I don't care about the privacy of the URLs I'm requesting against Google's server.

**Comment by bsurmanski** [comment]
What would be gained by using the Lookup API? Wouldn't it give the same result?

**Comment by heipei** [comment]
Yes, it would be the same results but the urls.search endpoint has 100k free lookups per month.

**Comment by JJLionHeart** [comment]
I am sorry, but what you are suggesting is not an approved use of the APIs. Please feel free to reach out to  web-risk-support@google.com if you have any other questions.
